
export const metadata = {
    title: 'Admin DashBoard',
    description: 'Generated by create next app',
  }

export default async function ClientLayout({children, params}){

    return(
       <>        
          {children}
       </>
    )
}